### ISSUE TITLE
Bug: script search input ellipsis isn't removed on focus

### ISSUE THREAD

**Issue by JeffreyNordlieTR** [FranciscoBiaso/TileMapEditorRealmz#10]
Clicking into the the script search input doesn't remove the placeholder ellipsis:

![image](https://user-images.githubusercontent.com/59657187/99196379-a04a7300-2751-11eb-8b63-491dfd817694.png)

**Comment by FranciscoBiaso** [comment]
Fixed!
ccae7f71077c6ef9020f6e128f23600cd29079e0
