### ISSUE TITLE
Enhancement: Allow renaming of images

### ISSUE THREAD

**Issue by JeffreyNordlieTR** [FranciscoBiaso/TileMapEditorRealmz#11]
Allow renaming of images similar to how script renaming works:

![image](https://user-images.githubusercontent.com/59657187/99196472-32527b80-2752-11eb-8952-7a36eb62dd87.png)

![image](https://user-images.githubusercontent.com/59657187/99196481-3e3e3d80-2752-11eb-90df-1eb925d4f56d.png)

**Comment by FranciscoBiaso** [comment]
Fixed!
705725a9c2a307fcfaef9ce1db22bd92c3037308
