### ISSUE TITLE
Enhancement (important!): Support multi-layer tiles

### ISSUE THREAD

**Issue by JeffreyNordlieTR** [FranciscoBiaso/TileMapEditorRealmz#13]
I believe the original roadmap included support for 2 layers per tile. A background layer and a layer for monsters, furniture, NPCs, etc. Unless I'm missing something I don't see a way to do this currently. It will be very important to support images with transparent backgrounds so that they can be dropped on a background. Is there a plan for this currently?

**Comment by FranciscoBiaso** [comment]
It is not activated but it is possible to use the current architecture to produce these effects. This choice was made by me due to the images we already have, all of them have a drawn background. This can be improved editing Cylinder class.

**Comment by JeffreyNordlieTR** [comment]
I submitted this as an enhancement to the code so it shouldn't be closed until a commit is merged supporting this functionality. Being limited by the original Realmz assets isn't great since we won't be able to drop any additional assets (which is a major feature) into the map builder. Can you explain further why this was closed?

**Comment by FranciscoBiaso** [comment]
Sorry to close this issue, I'm not a git hub expert. Let's keep it open until a merge occurs. Thanks!

**Comment by JeffreyNordlieTR** [comment]
Perfect, thanks! Standard practice is to create a new branch for each issue or feature you work on, push commits to that branch, then create a PR for the branch and reference the issue in the PR. There won't be anyone to code review the PR so you can just merge it but I strongly recommend following these best practices so we have a nice and thorough git history!

**Comment by FranciscoBiaso** [comment]
Of course, we will try to use the best practices from the git community.

**Comment by FranciscoBiaso** [comment]
Done!
Commit: 520444029518afc0bcf03fc719ba606a5bdcf9e1
