### ISSUE TITLE
Move entries from ressorces/app.json  to map_things.jso

### ISSUE THREAD

**Issue by SamuelRabreau** [FranciscoBiaso/TileMapEditorRealmz#15]
Data that should be included in the map like 
"map_width" : 85,
 "map_height" : 85,
 "map_levels": 4,
is still  in app.json . 
It should be included in the distributed map's data. i suggest the file map_things.json  along with the map name etc,  as what is already in the file map_info.json like camera position is useless for the game engine.

**Comment by FranciscoBiaso** [comment]
Fixed!
08665e57259bbdcfb9c78dd8e26a49b0c7203c3e
