### ISSUE TITLE
Usability: Suggestions to change how to scroll/pan the map

### ISSUE THREAD

**Issue by JeffreyNordlieTR** [FranciscoBiaso/TileMapEditorRealmz#2]
Holding space to pan the map view feels a bit awkward and non-standard. I suggest:

1. Add the ability to hold right-click to pan the view
2. Mouse wheel to zoom in/out
3. Add horizontal and vertical scrollbars when the map is zoomed in
4. Use shift + mouse wheel to change floors instead of ctrl. Shift is easier to use when quickly interacting with with app and creating maps.

1 & 2 together would make interacting with the map much easier and smoother!

**Comment by FranciscoBiaso** [comment]
O item 1 entrará em conflito com a funcionalidade de seleção de coisas.
