### ISSUE TITLE
Bug: Zooming causes mouse tile highlight position to be inaccurate

### ISSUE THREAD

**Issue by JeffreyNordlieTR** [FranciscoBiaso/TileMapEditorRealmz#3]
Repro steps:
1. Launch map editor
2. Mouse around the map
    - Notice that the tiles highlight properly as the mouse cursor passes over them
3. Zoom in or out a few times
4. Mouse around the map
    - Notice that the tiles that are highlighted are not underneath the mouse cursor

**Comment by FranciscoBiaso** [comment]
Fixed a7d180bf21871526ef515a90685a4745511f5082
