### ISSUE TITLE
Bug: Grid lines showing around tiles at random

### ISSUE THREAD

**Issue by JeffreyNordlieTR** [FranciscoBiaso/TileMapEditorRealmz#6]
Grid lines sometimes show when placing a tile and other times don't show. Not sure if they are supposed to or not.

![image](https://user-images.githubusercontent.com/59657187/99195367-d59f9280-274a-11eb-86ce-da65b5b2f57a.png)

**Comment by FranciscoBiaso** [comment]
Fixed!
188e6a42ca46ea81f04a0695e928c6d68d07720d
